-- ============================================================
-- AI Career Management Platform
-- Complete MySQL Database Schema
-- ============================================================
-- Database: ai_career_platform
-- Engine: InnoDB (all tables)
-- Charset: utf8mb4
-- ============================================================

-- Create Database
CREATE DATABASE IF NOT EXISTS ai_career_platform
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE ai_career_platform;

-- ============================================================
-- 1. Users & Authentication
-- ============================================================

CREATE TABLE users (
    id              INT             AUTO_INCREMENT PRIMARY KEY,
    email           VARCHAR(255)    NOT NULL,
    username        VARCHAR(100)    NOT NULL,
    hashed_password VARCHAR(255)    NOT NULL,
    full_name       VARCHAR(255)    NULL,
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,
    is_superuser    BOOLEAN         NOT NULL DEFAULT FALSE,
    created_at      DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    UNIQUE INDEX idx_users_email    (email),
    UNIQUE INDEX idx_users_username (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- ============================================================
-- 2. Career Profiles
-- ============================================================

CREATE TABLE career_profiles (
    id              INT             AUTO_INCREMENT PRIMARY KEY,
    user_id         INT             NOT NULL,

    -- Personal Information
    full_name       VARCHAR(255)    NULL,
    title           VARCHAR(255)    NULL,
    summary         TEXT            NULL,

    -- Professional Details (JSON columns)
    skills          JSON            NULL COMMENT 'Array of skills',
    experience_years INT            NULL,
    education       JSON            NULL COMMENT 'Array of education records [{school, degree, field, start, end}]',
    work_experience JSON            NULL COMMENT 'Array of work experiences [{company, title, start, end, description}]',

    -- Contact & Social
    contact_info    JSON            NULL COMMENT '{phone, address, city, country}',
    social_links    JSON            NULL COMMENT '{linkedin, github, portfolio, twitter}',

    -- AI-generated
    ai_skills_summary   TEXT        NULL COMMENT 'AI-generated skills analysis',
    ai_career_suggestions JSON     NULL COMMENT 'AI career path suggestions',

    created_at      DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    UNIQUE INDEX idx_career_profiles_user (user_id),
    CONSTRAINT fk_career_profiles_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- ============================================================
-- 3. CVs (Resumes)
-- ============================================================

CREATE TABLE cvs (
    id                  INT             AUTO_INCREMENT PRIMARY KEY,
    user_id             INT             NOT NULL,
    career_profile_id   INT             NULL,

    -- CV Metadata
    title               VARCHAR(255)    NOT NULL,
    version             VARCHAR(50)     NULL,
    description         TEXT            NULL,
    is_master           BOOLEAN         NOT NULL DEFAULT FALSE,
    is_public           BOOLEAN         NOT NULL DEFAULT FALSE,
    is_ai_generated     BOOLEAN         NOT NULL DEFAULT FALSE COMMENT 'Was this CV generated by AI?',

    -- Target Information (for tailored CVs)
    target_job_title    VARCHAR(255)    NULL,
    target_industry     VARCHAR(255)    NULL,
    target_company      VARCHAR(255)    NULL,

    -- File Information
    file_path           VARCHAR(500)    NULL,
    file_name           VARCHAR(255)    NULL,
    file_type           VARCHAR(50)     NULL COMMENT 'pdf, docx, etc.',
    file_size           INT             NULL COMMENT 'bytes',
    uploaded_at         DATETIME        NULL,

    -- AI Parsed Data
    ai_parsed_data      JSON            NULL COMMENT 'Structured data from AI CV parsing',
    ai_keywords         JSON            NULL COMMENT 'Extracted keywords array',
    ai_summary          TEXT            NULL COMMENT 'AI-generated CV summary',
    ai_score            INT             NULL COMMENT 'AI quality score 0-100',
    content_text        TEXT            NULL COMMENT 'Full extracted text content',

    created_at          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    INDEX idx_cvs_user          (user_id),
    INDEX idx_cvs_career_profile (career_profile_id),
    INDEX idx_cvs_is_master     (is_master),
    INDEX idx_cvs_title         (title),

    CONSTRAINT fk_cvs_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_cvs_career_profile
        FOREIGN KEY (career_profile_id) REFERENCES career_profiles(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- ============================================================
-- 4. Job Opportunities
-- ============================================================

CREATE TABLE job_opportunities (
    id              INT             AUTO_INCREMENT PRIMARY KEY,
    user_id         INT             NOT NULL,

    -- Job Details
    title           VARCHAR(255)    NOT NULL,
    company         VARCHAR(255)    NULL,
    location        VARCHAR(255)    NULL,
    job_type        ENUM('full_time','part_time','contract','internship','freelance','temporary')
                                    NOT NULL DEFAULT 'full_time',
    is_remote       BOOLEAN         NOT NULL DEFAULT FALSE,

    -- Compensation
    salary_min      INT             NULL,
    salary_max      INT             NULL,
    salary_currency VARCHAR(10)     NULL DEFAULT 'USD',

    -- Description
    description     TEXT            NULL,
    requirements    TEXT            NULL,
    responsibilities TEXT           NULL,
    benefits        TEXT            NULL,

    -- Source Information
    source          VARCHAR(255)    NULL COMMENT 'LinkedIn, Indeed, Company Website, etc.',
    source_url      VARCHAR(500)    NULL,
    external_id     VARCHAR(255)    NULL COMMENT 'ID from external job board',

    -- Status & Dates
    status          ENUM('open','closed','archived')
                                    NOT NULL DEFAULT 'open',
    posted_date     DATE            NULL,
    deadline        DATE            NULL,
    closed_date     DATE            NULL,

    -- AI Analysis
    ai_keywords     JSON            NULL COMMENT 'AI-extracted keywords from JD',
    ai_summary      TEXT            NULL COMMENT 'AI-generated summary of JD',
    ai_difficulty   INT             NULL COMMENT 'AI-estimated difficulty 1-5',

    created_at      DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    INDEX idx_jobs_user     (user_id),
    INDEX idx_jobs_status   (status),
    INDEX idx_jobs_company  (company),
    INDEX idx_jobs_title    (title),
    INDEX idx_jobs_type     (job_type),
    INDEX idx_jobs_deadline (deadline),

    CONSTRAINT fk_jobs_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- ============================================================
-- 5. Job Applications
-- ============================================================

CREATE TABLE job_applications (
    id                  INT             AUTO_INCREMENT PRIMARY KEY,
    user_id             INT             NOT NULL,
    job_opportunity_id  INT             NOT NULL,
    cv_id               INT             NULL,

    -- Application Details
    status              ENUM('draft','applied','screening','interview','offer','accepted','rejected','withdrawn')
                                        NOT NULL DEFAULT 'draft',
    application_date    DATETIME        NULL,
    deadline            DATETIME        NULL,

    -- Cover Letter
    cover_letter_content    TEXT        NULL,
    cover_letter_file_path  VARCHAR(500) NULL,
    cover_letter_ai_generated BOOLEAN   NOT NULL DEFAULT FALSE,

    -- Additional Information
    notes               TEXT            NULL,
    referral_source     VARCHAR(255)    NULL,
    referral_person     VARCHAR(255)    NULL,

    -- Application Tracking
    application_url     VARCHAR(500)    NULL,
    application_platform VARCHAR(100)   NULL COMMENT 'LinkedIn, Indeed, Company Portal, Email, etc.',

    -- AI Analysis
    ai_fit_score        INT             NULL COMMENT 'AI estimated fit score 0-100',
    ai_tips             TEXT            NULL COMMENT 'AI tips for this application',

    created_at          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    INDEX idx_applications_user      (user_id),
    INDEX idx_applications_job       (job_opportunity_id),
    INDEX idx_applications_cv        (cv_id),
    INDEX idx_applications_status    (status),
    INDEX idx_applications_date      (application_date),

    CONSTRAINT fk_applications_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_applications_job
        FOREIGN KEY (job_opportunity_id) REFERENCES job_opportunities(id) ON DELETE CASCADE,
    CONSTRAINT fk_applications_cv
        FOREIGN KEY (cv_id) REFERENCES cvs(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- ============================================================
-- 6. Interviews
-- ============================================================

CREATE TABLE interviews (
    id                  INT             AUTO_INCREMENT PRIMARY KEY,
    user_id             INT             NOT NULL,
    application_id      INT             NOT NULL,

    -- Interview Details
    interview_type      ENUM('phone','video','onsite','technical','behavioral','case_study','final_round')
                                        NOT NULL,
    title               VARCHAR(255)    NULL,
    description         TEXT            NULL,
    location            VARCHAR(500)    NULL,
    meeting_url         VARCHAR(500)    NULL,

    -- Scheduling
    scheduled_at        DATETIME        NOT NULL,
    duration_minutes    INT             NULL DEFAULT 60,
    timezone            VARCHAR(50)     NULL DEFAULT 'UTC',

    -- Interviewer Information
    interviewer_name    VARCHAR(255)    NULL,
    interviewer_title   VARCHAR(255)    NULL,
    interviewer_email   VARCHAR(255)    NULL,
    interviewer_phone   VARCHAR(50)     NULL,

    -- Status and Feedback
    status              ENUM('scheduled','completed','cancelled','rescheduled','no_show')
                                        NOT NULL DEFAULT 'scheduled',
    rating              INT             NULL COMMENT 'Self-rating 1-5',
    feedback            TEXT            NULL,
    notes               TEXT            NULL,

    -- AI Preparation
    ai_prep_questions   JSON            NULL COMMENT 'AI-generated interview prep questions',
    ai_prep_tips        TEXT            NULL COMMENT 'AI interview preparation tips',

    created_at          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    INDEX idx_interviews_user          (user_id),
    INDEX idx_interviews_application   (application_id),
    INDEX idx_interviews_status        (status),
    INDEX idx_interviews_scheduled     (scheduled_at),

    CONSTRAINT fk_interviews_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_interviews_application
        FOREIGN KEY (application_id) REFERENCES job_applications(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- ============================================================
-- 7. Follow-ups
-- ============================================================

CREATE TABLE follow_ups (
    id              INT             AUTO_INCREMENT PRIMARY KEY,
    user_id         INT             NOT NULL,
    application_id  INT             NULL,
    interview_id    INT             NULL,

    -- Follow-up Details
    follow_up_type  ENUM('email','phone_call','message','meeting','thank_you','follow_up_email','networking')
                                    NOT NULL,
    title           VARCHAR(255)    NULL,
    description     TEXT            NULL,
    priority        INT             NOT NULL DEFAULT 2 COMMENT '1=Low, 2=Medium, 3=High',

    -- Scheduling
    scheduled_at    DATETIME        NOT NULL,
    completed_at    DATETIME        NULL,

    -- Status
    status          ENUM('pending','completed','missed','cancelled')
                                    NOT NULL DEFAULT 'pending',

    -- Contact Information
    contact_person  VARCHAR(255)    NULL,
    contact_email   VARCHAR(255)    NULL,
    contact_phone   VARCHAR(50)     NULL,

    -- Notes
    notes           TEXT            NULL,
    outcome         TEXT            NULL,

    -- AI-generated
    ai_template     TEXT            NULL COMMENT 'AI-generated email/message template',

    created_at      DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    INDEX idx_follow_ups_user         (user_id),
    INDEX idx_follow_ups_application  (application_id),
    INDEX idx_follow_ups_interview    (interview_id),
    INDEX idx_follow_ups_status       (status),
    INDEX idx_follow_ups_scheduled    (scheduled_at),
    INDEX idx_follow_ups_priority     (priority),

    CONSTRAINT fk_follow_ups_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_follow_ups_application
        FOREIGN KEY (application_id) REFERENCES job_applications(id) ON DELETE CASCADE,
    CONSTRAINT fk_follow_ups_interview
        FOREIGN KEY (interview_id) REFERENCES interviews(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- ============================================================
-- 8. Documents
-- ============================================================

CREATE TABLE documents (
    id                  INT             AUTO_INCREMENT PRIMARY KEY,
    user_id             INT             NOT NULL,

    -- Document Metadata
    document_type       ENUM('cv','cover_letter','certificate','transcript','portfolio','job_description','other')
                                        NOT NULL,
    title               VARCHAR(255)    NULL,
    description         TEXT            NULL,
    tags                JSON            NULL COMMENT 'User-defined tags array',

    -- Related Entity (polymorphic)
    related_entity_type VARCHAR(50)     NULL COMMENT 'cv, application, job, etc.',
    related_entity_id   INT             NULL,

    -- File Information
    file_name           VARCHAR(255)    NOT NULL,
    file_path           VARCHAR(500)    NOT NULL,
    file_type           VARCHAR(50)     NOT NULL COMMENT 'MIME type: application/pdf, etc.',
    file_size           INT             NOT NULL COMMENT 'bytes',
    storage_path        VARCHAR(500)    NULL COMMENT 'Full path in blob/local storage',
    storage_provider    VARCHAR(50)     NULL DEFAULT 'local' COMMENT 'local or azure',

    -- AI Analysis
    ai_extracted_text   TEXT            NULL COMMENT 'AI-extracted text content',
    ai_summary          TEXT            NULL COMMENT 'AI-generated document summary',

    uploaded_at         DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    INDEX idx_documents_user          (user_id),
    INDEX idx_documents_type          (document_type),
    INDEX idx_documents_entity        (related_entity_type, related_entity_id),

    CONSTRAINT fk_documents_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- ============================================================
-- 9. CV-Job Match Results
-- ============================================================

CREATE TABLE cv_job_matches (
    id                  INT             AUTO_INCREMENT PRIMARY KEY,
    user_id             INT             NOT NULL,
    cv_id               INT             NOT NULL,
    job_opportunity_id  INT             NOT NULL,

    -- Match Results
    match_score         FLOAT           NOT NULL COMMENT 'Overall match score 0-100',
    match_details       JSON            NULL COMMENT 'Detailed matching breakdown',
    ai_analysis         JSON            NULL COMMENT 'Full AI analysis results',
    ai_recommendation   VARCHAR(500)    NULL COMMENT 'AI recommendation text',

    -- Category Scores
    skills_match_score      FLOAT       NULL,
    experience_match_score  FLOAT       NULL,
    education_match_score   FLOAT       NULL,
    keywords_match_score    FLOAT       NULL,

    -- AI-generated
    ai_tailored_cv_id       INT         NULL COMMENT 'Reference to AI-generated tailored CV',
    ai_cover_letter_text    TEXT        NULL COMMENT 'AI-generated cover letter for this match',

    created_at          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    INDEX idx_matches_user  (user_id),
    INDEX idx_matches_cv    (cv_id),
    INDEX idx_matches_job   (job_opportunity_id),
    INDEX idx_matches_score (match_score),

    CONSTRAINT fk_matches_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_matches_cv
        FOREIGN KEY (cv_id) REFERENCES cvs(id) ON DELETE CASCADE,
    CONSTRAINT fk_matches_job
        FOREIGN KEY (job_opportunity_id) REFERENCES job_opportunities(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- ============================================================
-- 10. Chat Messages (AI Chatbot)
-- ============================================================

CREATE TABLE chat_messages (
    id                  INT             AUTO_INCREMENT PRIMARY KEY,
    user_id             INT             NOT NULL,

    -- Session Management
    session_id          VARCHAR(100)    NOT NULL,
    conversation_title  VARCHAR(255)    NULL,

    -- Message Content
    role                ENUM('user','assistant','system')
                                        NOT NULL,
    content             TEXT            NOT NULL,

    -- Tool Calls (for AI agent actions)
    tool_calls          JSON            NULL COMMENT 'AI tool call records',
    tool_results        JSON            NULL COMMENT 'AI tool execution results',

    -- Metadata
    token_count         INT             NULL,
    model_used          VARCHAR(100)    NULL,
    processing_time_ms  INT             NULL,

    created_at          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    INDEX idx_chat_user      (user_id),
    INDEX idx_chat_session   (session_id),
    INDEX idx_chat_created   (created_at),

    CONSTRAINT fk_chat_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- ============================================================
-- 11. AI Agent Actions Log
-- ============================================================

CREATE TABLE ai_agent_actions (
    id              INT             AUTO_INCREMENT PRIMARY KEY,
    user_id         INT             NOT NULL,
    session_id      VARCHAR(100)    NOT NULL,

    -- Action Details
    action_type     VARCHAR(100)    NOT NULL COMMENT 'query, analyze, generate_cv, generate_cover_letter, match, etc.',
    action_input    JSON            NULL COMMENT 'Input parameters',
    action_output   JSON            NULL COMMENT 'Output results',
    action_status   ENUM('pending','running','completed','failed')
                                    NOT NULL DEFAULT 'pending',

    -- Performance
    tokens_used     INT             NULL,
    cost_estimate   FLOAT           NULL COMMENT 'Estimated cost in USD',
    duration_ms     INT             NULL,

    created_at      DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at    DATETIME        NULL,

    INDEX idx_agent_actions_user      (user_id),
    INDEX idx_agent_actions_session   (session_id),
    INDEX idx_agent_actions_type      (action_type),
    INDEX idx_agent_actions_status    (action_status),

    CONSTRAINT fk_agent_actions_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- ============================================================
-- 12. Notifications
-- ============================================================

CREATE TABLE notifications (
    id              INT             AUTO_INCREMENT PRIMARY KEY,
    user_id         INT             NOT NULL,

    -- Notification Content
    type            VARCHAR(50)     NOT NULL COMMENT 'interview_reminder, follow_up_due, application_update, etc.',
    title           VARCHAR(255)    NOT NULL,
    message         TEXT            NOT NULL,
    is_read         BOOLEAN         NOT NULL DEFAULT FALSE,

    -- Related Entity
    related_entity_type VARCHAR(50)  NULL,
    related_entity_id   INT         NULL,

    created_at      DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    INDEX idx_notifications_user     (user_id),
    INDEX idx_notifications_read     (is_read),
    INDEX idx_notifications_created  (created_at),

    CONSTRAINT fk_notifications_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- ============================================================
-- Seed Data: Demo User
-- Password: "demo123456" (bcrypt hash)
-- ============================================================

INSERT INTO users (email, username, hashed_password, full_name, is_active, is_superuser)
VALUES (
    'demo@aicareer.com',
    'demo',
    '$2b$12$LJ3m4ys3LkBCVxhJNhjZROGbnXmAjxrRsPXOqHwMkF9VqZqGqHqCi',
    'Demo User',
    TRUE,
    TRUE
);