"""
CV model for managing multiple resume versions.
"""
from sqlalchemy import Column, Integer, String, Text, DateTime, JSON, Boolean, ForeignKey
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from backend.database import Base


class CV(Base):
    """CV/Resume model."""
    __tablename__ = "cvs"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    career_profile_id = Column(
        Integer,
        ForeignKey("career_profiles.id", ondelete="CASCADE"),
        nullable=True
    )

    # CV Metadata
    title = Column(String(255), nullable=False)
    version = Column(String(50), nullable=True)
    description = Column(Text, nullable=True)
    is_master = Column(Boolean, default=False, nullable=False)
    is_public = Column(Boolean, default=False, nullable=False)
    is_ai_generated = Column(Boolean, default=False, nullable=False, comment="Was this CV generated by AI?")

    # Target Information (for tailored CVs)
    target_job_title = Column(String(255), nullable=True)
    target_industry = Column(String(255), nullable=True)
    target_company = Column(String(255), nullable=True)

    # File Information
    file_path = Column(String(500), nullable=True)
    file_name = Column(String(255), nullable=True)
    file_type = Column(String(50), nullable=True)  # pdf, docx, etc.
    file_size = Column(Integer, nullable=True)  # in bytes
    uploaded_at = Column(DateTime(timezone=True), nullable=True)

    # AI Parsed Data
    ai_parsed_data = Column(JSON, nullable=True)  # Structured data from AI parsing
    ai_keywords = Column(JSON, nullable=True)  # Extracted keywords
    ai_summary = Column(Text, nullable=True)  # AI generated summary
    ai_score = Column(Integer, nullable=True, comment="AI quality score 0-100")
    content_text = Column(Text, nullable=True)  # Full extracted text content

    # Timestamps
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False
    )

    # Relationships
    career_profile = relationship("CareerProfile", back_populates="cvs")
    applications = relationship("JobApplication", back_populates="cv")
    cv_job_matches = relationship("CVJobMatch", back_populates="cv", cascade="all, delete-orphan")

    def __repr__(self):
        return f"<CV(id={self.id}, title={self.title}, user_id={self.user_id})>"
